### ISSUE TITLE
Confusion around accessing the SSO dashboard

### ISSUE THREAD

**Issue by bloche** [pivotal-cf/docs-identity#102]
Tutorial of reference: https://docs.pivotal.io/p-identity/1-3/okta/config-okta.html

Hello, I'm attempting to set up my organization's Okta account as a SAML IdP, however following this tutorial I'm not sure how to sign into the SSO dashboard.

The tutorial says to go to `https://p-identity.YOUR-SYSTEM-DOMAIN` but I'm not sure what `YOUR-SYSTEM-DOMAIN` would be. I've tried using my org's `<orgname>.okta.com` domain and our org's admin domain with no luck.

Could you provide an example of a URL that we would navigate to to get to the SSO dashboard?

**Comment by radaeze** [comment]
@bloche I believe the answer to your question is sadly on another page: https://docs.pivotal.io/p-identity/1-8/system-plan.html#configure. 

```
Log into the SSO dashboard at https://p-identity.YOUR-SYSTEM-DOMAIN using your User Account and Authentication (UAA) administrator credentials.
In your Elastic Runtime tile in Ops Manager, the Domain settings show your system domain, and the Credentials tab shows the UAA Admin Credentials.
```

I will update the docs to make this guidance easier to find.

**Comment by bloche** [comment]
Ok great, thanks for the prompt response.

**Comment by jncd** [comment]
Improved now. @bloche check out https://docs.pivotal.io/p-identity/okta/config-okta.html
Thanks for your feedback.
And, thanks @radaeze for making the changes.
