### ISSUE TITLE
Please be specific with Network Selection

### ISSUE THREAD

**Issue by agregory999** [pivotal-cf/docs-identity#44]
When using a CF install that has 4 networks (infra, ERT, Services, Dedicated), there is no guidance on what to select for the Network, which is required.  The install guide should provide this guidance.

**Comment by sreetummidi** [comment]
Hi @agregory999 ,
Are you referring to the network for the SSO Tile?

Thanks,
Sree

**Comment by agregory999** [comment]
Hi Sree,

When I added the SSO tile, it needed the network, and the docs didn't mention what to do.  For example, the typical 3-AZ deployment has infrastructure, ert, services, and dynamic services networks.  I wasn't sure which of the first 2 to select.
Andrew

Andrew Gregory
Senior Platform Architect, New England
+1 617-529-0749 | agregory@pivotal.io <mailto:agregory@pivotal.io>



Transforming how the world builds software.

**Comment by agregory999** [comment]
Hi Sree,

I don't think the docs tell you what to do here...

http://docs.pivotal.io/p-identity/1-5/installation.html <http://docs.pivotal.io/p-identity/1-5/installation.html>

Under "Install SSO via Ops Manager" it should give guidance as to what to select in an enterprise deployment.



Andrew Gregory
Senior Platform Architect, New England
+1 617-529-0749 | agregory@pivotal.io <mailto:agregory@pivotal.io>



Transforming how the world builds software.

**Comment by tnwang** [comment]
SSO Identity Service Broker is deployed as an app onto CF, so the network likely will not matter since the ERT Cloud Controller APIs and ERT UAA APIs should be exposed regardless of network.  SSO uses CF routing instead of its own BOSH VM IPs since it doesn't have its own BOSH VM.

The `Deployment` (a.k.a. ERT) network is the best bet.

**Comment by agregory999** [comment]
Thank you Tian - could the doc mention that so there is no ambiguity for enterprise deployments.

Andrew Gregory
Senior Platform Architect, New England
+1 617-529-0749 | agregory@pivotal.io <mailto:agregory@pivotal.io>



Transforming how the world builds software.

**Comment by tnwang** [comment]
This issue should already have raised a story in the Docs backlog - once they get around to it, I can work with them to get this added as a note for installation page.

```
Note: SSO Identity Service Broker is deployed as a CF app from a BOSH errand, and has no associated BOSH VMs that require selecting a corresponding network. If you are forced to select a network during installation to select a network, you can select the `Deployment` (a.k.a `ERT` or `PAS`) network.
```

**Comment by bentarnoff** [comment]
Thanks @tnwang and @agregory999. We've made the suggested change to the docs, which you can see here: https://docs.pivotal.io/p-identity/1-5/installation.html#install. I'm closing this issue, but please feel free to get in touch if you have any further questions or concerns.
