### ISSUE TITLE
CLI for p-identity

### ISSUE THREAD

**Issue by fordagertz** [pivotal-cf/docs-identity#50]
Is there any way to read SSO plan administrators with a privileged UAAC account from the CLI? We would like to automate reading our configs to produce a report for the plan admins that can serve as evidence of an access review.

Also wanting to know if there is any way to write configuration (sso plan administrators or assigned orgs) from the CLI for other automations?

**Comment by jncd** [comment]
@tnwang Can you address @fordagertz 's questions here?

**Comment by tnwang** [comment]
SSO service plans leverage UAA identity zones (https://docs.cloudfoundry.org/uaa/uaa-concepts.html#iz), and plan administrators are identity zone administrators using scopes like `zones.ZONE-ID.admin`. SSO brokers the creation and assignment of these scopes for operators when plans are created and plan administrators are assigned.

@jncd Could we document this as part of http://docs.pivotal.io/p-identity/1-6/manage-service-plans.html for SSO 1.6 and future SSO versions under a section called `Advanced Service Plan Details` or something? We can work on that together.

**Comment by tnwang** [comment]
SSO 1.8 once released will include docs that resolve this issue. Closing for now.
