### ISSUE TITLE
Docs for SSO 1.7.1 not released

### ISSUE THREAD

**Issue by aegershman** [pivotal-cf/docs-identity#67]
[The latest release notes for p-identity 1.7.* is 1.7.0](https://docs.pivotal.io/p-identity/1-7/release-notes.html); however, [1.7.1 was released and made available on pivnet](https://network.pivotal.io/products/pivotal_single_sign-on_service/). Just figured I'd give a heads up that the doc doesn't appear in sync with the current latest release

**Comment by Pivotal-Christopher-Wong** [comment]
Hi @aegershman! Thank you for reaching out to us! The newest version is now available. You can see it here: https://docs.pivotal.io/p-identity/1-7/release-notes.html#171
