### ISSUE TITLE
Configuring Azure Active Directory as a SAML Identity Provider shows using old Azure Portal

### ISSUE THREAD

**Issue by mattdot** [pivotal-cf/docs-identity#73]
https://docs.pivotal.io/p-identity/1-7/azure/config-azure.html shows configuration using the old Azure portal and not the new Azure portal at https://portal.azure.com/ .  These instructions can't be followed anymore.

**Comment by tnwang** [comment]
Updated docs are live now.

**Comment by kristopherjturner** [comment]
Where are the updated docs?  This current documentation still shows the Classic Azure.

**Comment by kristopherjturner** [comment]
https://docs.run.pivotal.io/sso/azure/config-azure.html was the link I was using.  Which is still using Azure Classic and not ARM.  The link at the top of this feed goes to a correct documentation now.

**Comment by jncd** [comment]
Hi @tnwang and @peterhaochen47 
Looks like this got updated for the PCF docs but not for the PWS docs. 
Can we set up a pairing session to run through the procedure in https://docs.pivotal.io/p-identity/azure/config-azure.html to see if it works the same for PWS?

**Comment by radaeze** [comment]
@kristopherjturner The link you referred to has been updated : https://docs.run.pivotal.io/sso/azure/config-azure.html
